repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: py -m pylint  # Chama o pylint corretamente na venv
        language: system
        types: [python]
        args:
          [
            "-rn",
            "-sn",
            "--rcfile=.pylintrc",
            "--load-plugins=pylint.extensions.docparams",
          ]
